apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rest
  labels: 
    app: nginx
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80