apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-in-peace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: rest
          image: aman2000verma/rest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
